[package]
name = "mpd-webthing"
version = "1.0.0"
authors = ["Michael Stegeman"]

[dependencies]
mpd = "0.0"
rand = "0.5"
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4"] }
webthing = "0.8"

[[bin]]
name = "mpd-webthing"
path = "src/mpd-webthing.rs"
